version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/system-engineering
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/app-stop.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install-pkgs.sh
      timeout: 1200
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 300
      runas: ubuntu